# Generated by Django 2.2.26 on 2022-10-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userdetails_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='username',
        ),
    ]
