# Generated by Django 2.2.26 on 2022-10-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userdetails_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
