# Generated by Django 2.2.26 on 2022-10-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='app',
        ),
    ]
